- name: install cart component
  hosts: cart
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install cart
    ansible.builtin.package:
     name: nodejs
     state: present
    
  - name: create roboshop
    ansible.builtin.user:
     name: roboshop
       
  - name: creating directory
    ansible.builtin.file:
     path: /app
     state: directory 

  - name: downloading cart application
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     dest: /tmp 

  - name: extract cart
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: Copy cart service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service
    

  - name: daemon_reload 
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: start and enable cart
    ansible.builtin.service:
        name: cart
        state: started
        enabled: yes