- name: install web componends
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove html directory
    ansible.builtin.file:
      path: /user/share/nginx/html
      state: directory

   
